# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximum Number of OpenMP Threads
#'
#' Reports the number of threads _OpenMP_ would use on this machine.
#'
#' @return
#' An `integer` with the maximum number of _OpenMP_ threads, or `0` when the
#' package was built without _OpenMP_ support.
#'
#' @export
#' @examples
#' max_cores()
max_cores <- function() {
    .Call(`_RcppRNGParallel_max_cores`)
}

#' Draw Uniform Variates in Parallel with Independent Streams
#'
#' Samples from a uniform distribution in parallel, giving each thread its own
#' independent substream of a single seeded `dqrng` generator so that no two
#' threads ever produce the same values.
#'
#' @param n       Number of values to generate.
#' @param min     Lower bound of the continuous uniform distribution.
#' @param max     Upper bound of the continuous uniform distribution.
#' @param seed    Seed for the base random number generator.
#' @param n_cores Number of threads to use.
#'
#' @return
#' A `numeric` vector of length `n`.
#'
#' @details
#' A single `dqrng::xoshiro256plus` generator is seeded once. Inside the
#' parallel region each thread copies that generator and advances it with
#' `long_jump()` by an amount unique to the thread, which lands it on a
#' non-overlapping substream. The result is reproducible for a fixed `seed`
#' and `n_cores`. This is the correction to the naive approach of giving each
#' thread a default-constructed engine, which would leave every thread drawing
#' the same sequence.
#'
#' @export
#' @examples
#' # 100 draws across 2 threads, reproducible for this seed and core count.
#' draw_numeric_unif(100, n_cores = 2, seed = 42)
draw_numeric_unif <- function(n, min = 0.0, max = 1.0, seed = 42L, n_cores = 1L) {
    .Call(`_RcppRNGParallel_draw_numeric_unif`, n, min, max, seed, n_cores)
}

